using System;
using System.Collections.Generic;

#nullable disable

namespace DMS.Core.Models.Maintenance
{
    public partial class ErrorLog
    {
        public int Id { get; set; }
        public string DepotCode { get; set; }
        public string Route { get; set; }
        public string ExceptionTitle { get; set; }
        public string ExceptionDetails { get; set; }
        public string ReportedById { get; set; }
        public int? ApplicationId { get; set; }
        public bool? IsAutoGenerated { get; set; }
        public bool? IsSolved { get; set; }
        public int? ErrorCriticalIndex { get; set; }
        public DateTime? CreatedOn { get; set; }
    }
}
